import React from "react";
import '../styles/about.scss';

export default function TermsAndConditions() {
  return (
    <div className="about">
      Terms and Conditions ("Terms") Our Terms and Conditions were last updated
      on [DATE]. Please read these terms and conditions carefully before using
      Our Service. Interpretation and Definitions Interpretation The words of
      which the initial letter is capitalized have meanings defined under the
      following conditions. The following definitions shall have the same
      meaning regardless of whether they appear in singular or in plural.
      Definitions For the purposes of these Terms and Conditions: ● “Affiliate”
      means an entity that controls, is controlled by or is under common control
      with a party, where "control" means ownership of 50% or more of the
      shares, equity interest or other securities entitled to vote for election
      of directors or other managing authority. ● “Account” means a unique
      account created for You to access our Service or parts of our Service. ●
      “Company” (referred to as either "the Company", "We", "Us" or "Our" in
      this Agreement) refers to [COMPANY_INFORMATION]. ● “Country” refers to
      [COMPANY_COUNTRY]. ● “Content” refers to content such as text, images, or
      other information that can be posted, uploaded, linked to or otherwise
      made available by You, regardless of the form of that content. ● “Device”
      means any device that can access the Service such as a computer, a
      cellphone or a digital tablet. ● “Feedback” means feedback, innovations or
      suggestions sent by You regarding the attributes, performance or features
      of our Service. ● “Products” refer to the products or items offered for
      sale on the Service. ● “Orders” mean a request by You to purchase Products
      from Us. ● “Promotions” refer to contests, sweepstakes or other promotions
      offered through the Service. ● “Service” refers to the Website. ● “Terms
      and Conditions” (also referred as "Terms") mean these Terms and Conditions
      that form the entire agreement between You and the Company regarding the
      use of the Service. This Terms and Conditions Agreement was generated by
      TermsFeed Terms and Conditions Generator. ● “Third-party Social Media
      Service” means any services or content (including data, information,
      products or services) provided by a third-party that may be displayed,
      included or made available by the Service. ● “Website” refers to
      [WEBSITE_NAME], accessible from [WEBSITE_URL] ● “You” means the individual
      accessing or using the Service, or the company, or other legal entity on
      behalf of which such individual is accessing or using the Service, as
      applicable. Acknowledgment These are the Terms and Conditions governing
      the use of this Service and the agreement that operates between You and
      the Company. These Terms and Conditions set out the rights and obligations
      of all users regarding the use of the Service. Your access to and use of
      the Service is conditioned on Your acceptance of and compliance with these
      Terms and Conditions. These Terms and Conditions apply to all visitors,
      users and others who access or use the Service. By accessing or using the
      Service You agree to be bound by these Terms and Conditions. If You
      disagree with any part of these Terms and Conditions then You may not
      access the Service. You represent that you are over the age of 18. The
      Company does not permit those under 18 to use the Service. Your access to
      and use of the Service is also conditioned on Your acceptance of and
      compliance with the Privacy Policy of the Company. Our Privacy Policy
      describes Our policies and procedures on the collection, use and
      disclosure of Your personal information when You use the Application or
      the Website and tells You about Your privacy rights and how the law
      protects You. Please read Our Privacy Policy carefully before using Our
      Service.
    </div>
  );
}
