export const FETCH_USER_DETAILS = "FETCH_USER_DETAILS";
export const SET_BY_DEFAULT_USER_DETAILS = "SET_BY_DEFAULT_USER_DETAILS";
export const SET_RADIO_BUTTON_DATA = "SET_RADIO_BUTTON_DATA";

//Chat messages
export const SET_CHAT_MESSAGES = "SET_CHAT_MESSAGES";
export const ADD_NEW_CHAT = "ADD_NEW_CHAT";
export const REMOVE_CHAT = "REMOVE_CHAT";
export const REMOVE_CHAT_MESSAGES = "REMOVE_CHAT_MESSAGES";

//LOGIN DETAILS :
export const SET_BY_DEFAULT_LOGIN_DETAILS = "SET_BY_DEFAULT_LOGIN_DETAILS";
export const SET_LOGIN_CREDENTIALS = "SET_LOGIN_CREDENTIALS";

//UUID
export const FETCH_UUID_DATA = "FETCH_UUID_DATA";
export const ADD_EXISTING_CHAT = "ADD_EXISTING_CHAT";

//CLEAR ALL REDUX
export const SET_DEFAULT_VALUE = "SET_DEFAULT_VALUE";



